CREATE TABLE `user` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '用户ID',
  `username` VARCHAR(50) NOT NULL COMMENT '用户名',
  `password` VARCHAR(255) NOT NULL COMMENT '密码',
  `status` INT(11) NOT NULL DEFAULT 1 COMMENT '账号状态 1:启用 0:禁用 -1:删除',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `mobile` VARCHAR(20) DEFAULT NULL COMMENT '手机号',
  `email` VARCHAR(100) DEFAULT NULL COMMENT '邮箱',
  `last_login_ip` VARCHAR(50) DEFAULT NULL COMMENT '最后登录IP',
  `login_fail_count` INT(11) DEFAULT 0 COMMENT '连续登录失败次数',
  `lock_time` DATETIME DEFAULT NULL COMMENT '账号锁定时间',
  `remark` VARCHAR(500) DEFAULT NULL COMMENT '备注',
  `creator_id` VARCHAR(50) DEFAULT NULL COMMENT '创建人ID',
  `updater_id` VARCHAR(50) DEFAULT NULL COMMENT '最后修改人ID',
  `last_login_time` DATETIME DEFAULT NULL COMMENT '最后登录时间',
  `is_admin` TINYINT(1) DEFAULT 0 COMMENT '是否管理员',
  `role_id` VARCHAR(50) DEFAULT NULL COMMENT '角色ID',
  `avatar` VARCHAR(255) DEFAULT NULL COMMENT '头像地址',
  `gender` TINYINT(4) DEFAULT 0 COMMENT '性别 0:未知 1:男 2:女',
  `birthday` DATE DEFAULT NULL COMMENT '生日',
  `is_deleted` INT(11) NOT NULL DEFAULT 0 COMMENT '逻辑删除 0:未删除 1:已删除',
  PRIMARY KEY (`id`),
  INDEX `idx_username` (`username`),
  INDEX `idx_mobile` (`mobile`),
  INDEX `idx_email` (`email`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='用户表';
