server:
  port: 8001

spring:
  application:
    name: de-user
  main:
    web-application-type: reactive
      
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/deserted_hotel?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
  mail:
    host: smtp.example.com # 邮件服务器地址
    port: 465
    username: your-email@example.com
    password: your-email-password
    protocol: smtps
    properties:
      mail:
        smtp:
          ssl:
            enable: true
          auth: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000

mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

pagehelper:
  helper-dialect: mysql   # 数据库方言
  reasonable: true        # 分页合理化（pageNum<=0时自动设为1）
  support-methods-arguments: true # 支持接口参数直接传递
  params: count=countSql  # 统计查询配置 
